### ISSUE TITLE
Use chrono from original repo

### ISSUE THREAD

**Issue by rafaismyname** [wearerobos/text-juicer#2]
We should be using chrono from its original repo, and remove the files from here.
If the pull-request don't get approved (or while we wait until it gets approved), we should use as a fork.

**Comment by jpenna** [comment]
It wasn't in pull request. I have to do all the tests based on Chrono test's template, and I didn't yet.

So I created a new branch in my Chrono repo, named 'text-juicer', and pushed the 'chrono-ptbr' there. The dependency is pointing to this branch. 

I created a new card for Chrono tests
